[package]
name = "inf-edit"
version = "1.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
colored = "3.0.0"
crossterm = "0.29.0"
portable-pty = "0.9.0"
ratatui = "0.29.0"
tui-term = "0.2.0"
walkdir = "2.5.0"
